export default {
    layout: {
        brand: 'e口乐网页管理',
        navigation: {
            'change-log': '更新日志',
            dashboard: '主页',
            items: '商品',
            login: '登录',
            logout: '登出',
            orders: '订单',
            profile: '个人资料',
            settings: '网页设置',
            shop: '前往商店',
            users: '员工账户管理',
            wiki: '帮助与使用手册',
        },
    },
    auth: {
        login: {
            password: '密码',
            remember: '保持登录',
            title: '登录',
            username: '账户 ID',
        },
    },
    'change-log': {
        'current-version': '当前版本',
        title: '更新日志',
        'updated-at': '更新日期：{date}',
        'version-date': '{name}（{date}）',
    },
    wiki: {
        'clear-search': '清除搜索',
        contents: '本页目录',
        description:
            '通过图文说明掌握管理员日常功能，包括销售报表、商品维护、订单处理、员工权限与网站设置。',
        eyebrow: 'e口乐营运指南',
        'guide-number': '指南 {number}',
        'no-results': {
            description: '请尝试商品、订单、员工或设置等较宽泛的关键词。',
            title: '找不到符合搜索条件的指南',
        },
        'open-module': '打开此功能',
        'open-screenshot': '打开{title}截图',
        'result-count': '显示 {visible} / {total} 篇指南',
        'screenshot-alt': '{title}管理员页面',
        'screenshot-title': '{title}截图',
        'search-label': '查找指南',
        'search-placeholder': '搜索功能、操作或关键词',
        title: '管理员使用手册',
        'view-screenshot': '查看完整截图',
        categories: {
            account: '账户',
            administration: '系统管理',
            catalog: '商品目录',
            insights: '数据分析',
            operations: '日常营运',
            reference: '参考资料',
        },
        articles: {
            dashboard: {
                access: '所有已登录员工均可使用。',
                caption: '销售周期筛选与四项销售指标集中显示在仪表板中。',
                points: {
                    1: '选择每日、每周、每月或每年报表，再使用对应的日期控件切换到需要查看的周期。',
                    2: '从摘要卡片查看已完成订单、售出商品、销售收入与已取消订单金额。',
                    3: '切换筛选条件时只会刷新报表数据，页面位置与当前操作状态会被保留。',
                },
                summary:
                    '仪表板以统一方式呈现所选周期内的已完成销售与已取消商品金额，方便快速掌握营运情况。',
                title: '销售仪表板',
            },
            catalog: {
                access: '观察员可浏览；编辑员与监督员可使用更多商品操作。',
                caption: '搜索、筛选、排序、上架状态与商品卡片集中在同一页面。',
                points: {
                    1: '按商品名称、货号、规格、出产地或描述搜索，再通过分类缩小结果范围。',
                    2: '使用缺货与未上架筛选找出需要处理的商品，并在大量商品中切换排序方式。',
                    3: '从页首创建商品，或打开现有商品卡片编辑资料及控制商品是否显示在商店。',
                },
                summary:
                    '商品目录是查找商品、检查库存与上架状态，以及开始维护商品资料的主要工作区。',
                title: '商品目录',
            },
            'item-editor': {
                access: '编辑员可维护商品；删除等操作需要监督员或更高权限。',
                caption: '商品窗口以分页整理基本信息、规格、照片与计数器。',
                points: {
                    1: '在“基本信息”填写中英文名称、商品描述、出产地与分类。',
                    2: '维护每个规格的货号、中英文名称、原价与促销价、重量、库存及指定照片。',
                    3: '在“照片”上传商品图，在“其他”查看或重置计数器，并在资料完整后才将商品上架。',
                },
                summary:
                    '打开商品即可维护商店所需的完整资料，包括双语内容、规格、照片、上架状态与浏览销售计数。',
                title: '商品资料与上架',
            },
            orders: {
                access: '所有员工可查看订单；可执行的更新操作取决于账户权限。',
                caption:
                    '订单表格集中显示编号、交付方式、付款方式、总额与状态。',
                points: {
                    1: '按日期与交付方式筛选订单，专注处理当前的外送或预购取货队列。',
                    2: '打开订单查看顾客联系资料、邮寄信息、购买商品、备注与上传的付款收据。',
                    3: '使用账户获准的控件更新订单状态，并在需要时记录邮寄追踪 ID。',
                },
                summary:
                    '使用订单页面检查新订单与付款资料，并跟进每笔外送或预购取货订单的处理进度。',
                title: '订单处理',
            },
            staff: {
                access: '只有管理员可以打开员工账户管理。',
                caption: '员工账户会显示账户 ID，并提供账户编辑入口。',
                points: {
                    1: '使用账户 ID、密码、确认密码及最适合的最低权限等级创建员工账户。',
                    2: '当登录资料或工作职责改变时编辑现有账户。',
                    3: '观察员适合只读工作；编辑员处理日常商品与订单；监督员可进行更广泛的商品与设置管理。',
                },
                summary:
                    '管理员可在此创建和维护员工登录账户，并为每位员工配置合适的营运权限。',
                title: '员工账户与权限',
            },
            settings: {
                access: '所有员工可查看设置；更新功能取决于账户获授的权限。',
                caption: '出产地、分类、运费与免运规则集中在网站设置页面。',
                points: {
                    1: '维护双语出产地与分类，让商品能在商店中保持一致的整理与筛选方式。',
                    2: '查看结账时使用的基本运费。',
                    3: '当相关控件启用时，设置免运开关、订单门槛与显示给顾客的说明。',
                },
                summary: '网站设置保存商店共用的商品标签与结账规则。',
                title: '网站设置',
            },
            profile: {
                access: '每位已登录员工都有个人资料页面。',
                caption: '个人资料把当前账户 ID 与密码控件集中在同一处。',
                points: {
                    1: '确认目前使用的账户 ID；如需更改，请联系管理员。',
                    2: '当系统部署已启用密码更新功能时，可使用密码区域修改密码。',
                    3: '从导航栏的语言控件切换中文或英文；系统会为已登录账户保存选择。',
                },
                summary:
                    '个人资料用于确认当前登录账户，并提供员工个人安全与语言设置。',
                title: '个人资料与语言',
            },
            'change-log': {
                access: '已登录员工与进入管理员登录区的访客均可查看更新日志。',
                caption:
                    '展开版本分组即可查看按日期整理的功能、改进与修复内容。',
                points: {
                    1: '先查看页面顶部的版本名称与更新日期，再阅读近期变更。',
                    2: '展开版本分组，阅读按日期整理的新功能、改进与修复。',
                    3: '使用语言控件切换完整的中英文更新说明。',
                },
                summary:
                    '更新日志说明各版本之间的变化，帮助员工快速了解新加入或调整的功能。',
                title: '更新日志',
            },
        },
    },
    dashboard: {
        description: '查看所选时段内已完成的销售和已取消订单金额。',
        'fallback-user': '管理员',
        filters: {
            'date-formats': {
                daily: 'yy年 m月 d日',
                monthly: 'yy年 m月',
                weekly: 'yy年 m月 d日',
                yearly: 'yy年',
            },
            'date-labels': {
                daily: '日期',
                monthly: '月份',
                weekly: '所在周',
                yearly: '年份',
            },
            description: '选择报表时段及该时段包含的日期。',
            period: '报表时段',
            title: '销售时段',
        },
        'latest-order': '最新订单',
        'most-clicked-today': '今日最多点击商品',
        'no-notifications': '暂无通知',
        periods: {
            daily: '每日',
            monthly: '每月',
            weekly: '每周',
            yearly: '每年',
        },
        summary: {
            'canceled-order-value': {
                description: '已取消或已退款订单的商品金额，不含运费。',
                label: '已取消或已退款订单金额',
            },
            'completed-orders': {
                description: '状态为已完成的订单。',
                label: '已完成订单',
            },
            'items-sold': {
                description: '已完成订单中的商品总件数。',
                label: '售出商品',
            },
            'sales-revenue': {
                description: '已完成订单的商品金额，不含运费。',
                label: '销售收入',
            },
            title: '销售摘要',
        },
        title: '主页',
        welcome: '欢迎回来，{username}！',
    },
    profile: {
        'account-id': '账户 ID',
        'account-id-description': '您的账户 ID 为',
        'account-id-help': '**账户 ID 需要联系网页管理员以进行修改。',
        'change-password': '更换密码',
        'confirm-password': '确认密码',
        'new-password': '新密码',
        'old-password': '旧密码',
        'password-update-failed': '无法更新密码，请检查表格后重试。',
        'password-updated-success': '密码已成功更新。',
        title: '个人资料',
    },
    users: {
        'access-level': '权限',
        'access-level-details': '权限详情',
        active: '已启用',
        'add-account': '添加员工账户',
        'confirm-password': '密码确认',
        'create-account': '创建账户',
        'created-success': '用户创建成功。',
        'deactivate-account': '停用“{username}”',
        'deactivate-confirmation':
            '确定要停用“{username}”吗？该用户将被登出，并且无法再次登录。',
        'deactivate-failed': '无法停用此账户。',
        'deactivate-title': '停用员工账户',
        deactivated: '已停用',
        'deactivated-success': '用户已成功停用。',
        'delete-account': '删除“{username}”',
        'delete-confirmation':
            '确定要删除“{username}”吗？账户将被移除，其账户 ID 可供再次使用。',
        'delete-failed': '无法删除此账户。',
        'delete-title': '删除员工账户',
        'deleted-success': '用户已成功删除。',
        edit: '编辑',
        'edit-account': '编辑“{username}”',
        'editor-details':
            '可查看、创建和更新商品，可查看订单、更新处理中的订单状态和外送追踪 ID，并可查看所有网页设置。',
        password: '密码',
        'reactivate-account': '重新启用“{username}”',
        'reactivate-confirmation':
            '确定要重新启用“{username}”吗？该用户将可以再次登录。',
        'reactivate-failed': '无法重新启用此账户。',
        'reactivate-title': '重新启用员工账户',
        'reactivated-success': '用户已成功重新启用。',
        'supervisor-details':
            '可查看、创建、更新和删除商品，可查看订单、更新所有订单状态和外送追踪 ID，并可查看和更新所有网页设置。',
        title: '员工账户管理',
        'updated-success': '用户修改成功。',
        username: '账户 ID',
        'viewer-details': '可查看所有商品、订单和网页设置。',
    },
    orders: {
        columns: {
            barcode: '货号',
            date: '日期',
            'delivery-mode': '种类',
            'item-count': '商品数量',
            name: '名称',
            'payment-method': '付款方式',
            price: '价格（RM）',
            quantity: '数量',
            reference: '编号',
            status: '状态',
            total: '总计（RM）',
        },
        'customer-address': '顾客地址',
        'customer-name': '顾客名称',
        'customer-phone': '顾客电话号码',
        'date-filter': '订单日期',
        'date-format': 'yy年 m月 d日',
        'delivery-mode': {
            delivery: '外送',
            'self-pickup': '预购取货',
        },
        'delivery-tracking-id': '邮寄追踪 ID',
        'download-order': '下载订单',
        'item-details': '商品详情（{count} 个）',
        note: '备注',
        'order-details': '订单详情',
        'order-mode-filter': '全部订单模式',
        'receipt-dialog-title': '订单 {reference} 的收据',
        'receipt-image-alt': '订单 {reference} 上传的收据',
        'shipping-fee': '运费',
        'shipping-information': '邮寄资料',
        'status-update-failed': '无法更新订单状态。',
        'status-updated-success': '订单状态已更新。',
        status: {
            canceled: '已取消',
            completed: '已完成',
            pending: '处理中',
            ready: '准备就绪',
            refunded: '已退款',
        },
        title: '订单查看',
        'tracking-required': '订单离开处理中状态前，请先输入邮寄追踪 ID。',
        'tracking-update-failed': '无法更新邮寄追踪 ID。',
        'tracking-updated-success': '邮寄追踪 ID 已更新。',
        'view-receipt': '查看收据',
    },
    settings: {
        'add-category': '添加类别',
        'add-origin': '添加出产地',
        category: '类别',
        'category-filter': '类别过滤',
        'catalog-created-success': '{subject}创建成功。',
        'catalog-delete-confirmation':
            '确定要删除{subject}“{name}”吗？此操作无法撤销。',
        'catalog-delete-failed': '无法删除此{subject}。',
        'catalog-deleted-success': '{subject}删除成功。',
        'catalog-in-use': '此{subject}已用于 {count} 件商品，因此无法删除。',
        'catalog-save-failed': '无法保存此{subject}。',
        'catalog-updated-success': '{subject}更新成功。',
        'create-subject': '创建{subject}',
        'default-category-delete-disabled': '默认类别无法删除。',
        'delete-subject': '删除{subject}',
        'edit-subject': '编辑{subject}“{name}”',
        'free-shipping-after': '后即可包邮',
        'free-shipping-description-input': '免运备注',
        'free-shipping-note': '免运备注',
        'free-shipping-threshold-input': '免运订单门槛',
        'free-shipping-toggle': '启用免运',
        'free-shipping-update-failed': '无法更新免运设置。',
        'free-shipping-updated-success': '免运设置已更新。',
        'name-en': '名字（英文）',
        'name-zh': '名字（中文）',
        note: '备注',
        origin: '出产地',
        'origin-filter': '出产地过滤',
        'over-amount': '超过 RM',
        price: '价格',
        shipping: '邮费',
        'shipping-discount': '邮费折扣',
        'shipping-fee-input': '邮费',
        'shipping-update-failed': '无法更新邮费。',
        'shipping-updated-success': '邮费已更新。',
        title: '网页设置',
    },
    items: {
        'created-success': '商品创建成功！',
        'create-item': '创建商品',
        'create-title': '创建商品',
        'delete-confirmation': '确定要删除“{name}”吗？此操作无法撤销。',
        'delete-failed': '无法删除商品。',
        'delete-item': '删除“{name}”',
        'delete-title': '删除商品',
        'deleted-success': '商品删除成功！',
        'edit-item': '编辑商品',
        'edit-named-item': '编辑“{name}”',
        fields: {
            categories: '分类',
            description: '商品详情',
            name: '商品名称',
            'name-en': '商品名称（英文）',
            origin: '出产地',
            'origin-value': '出产于 {name}，{nameEn}',
        },
        images: {
            add: '添加商品照片',
            'remove-confirmation': '确定要删除“{name}”吗？此操作无法撤销。',
            'remove-failed': '无法删除商品照片。',
            'remove-image': '删除“{name}”',
            'remove-title': '删除商品照片',
            'removed-success': '商品照片删除成功！',
            'upload-failed': '无法将上传的照片添加到商品。',
            'uploaded-success': '商品照片上传成功！',
        },
        'list-item': '上架“{name}”',
        'listed-success': '商品上架成功！',
        'listing-requirements':
            '上架前，请填写商品的中英文名称、描述、出产地，并至少添加一个已填写货号及中英文名称的规格。',
        'listing-update-failed': '无法更新商品上架状态。',
        miscellaneous: {
            feature: '功能',
            'reset-action': '重置按钮',
            'reset-confirmation': '确定要将{counter}重置为 0 吗？',
            'reset-counter': '重置{counter}',
            'reset-failed': '无法重置{counter}。',
            'reset-success': '{counter}重置成功！',
            'reset-title': '重置{counter}',
            'sold-count': '销售量',
            value: '数值',
            'view-count': '浏览次数',
        },
        'no-variations': '无规格',
        tabs: {
            basic: '基本信息',
            images: '照片',
            miscellaneous: '其他',
            variations: '规格',
        },
        title: '商品管理',
        'unlist-item': '下架“{name}”',
        'unlisted-success': '商品下架成功！',
        'update-failed': '无法更新商品资料。',
        'updated-success': '商品资料更新成功！',
        variation: {
            'add-photo': '添加照片',
            'add-variation': '添加规格',
            barcode: '货号',
            'change-photo': '更换照片',
            'create-failed': '无法创建规格。',
            'create-title': '创建规格',
            'created-success': '规格创建成功！',
            'delete-confirmation': '确定要删除“{name}”吗？此操作无法撤销。',
            'delete-failed': '无法删除规格。',
            'delete-title': '删除规格',
            'delete-variation': '删除“{name}”',
            'deleted-success': '规格删除成功！',
            'edit-title': '编辑规格',
            'edit-variation': '编辑“{name}”',
            name: '名称',
            'name-en': '名称（英语）',
            photo: '规格照片',
            'photo-upload-failed': '无法将上传的照片添加到规格。',
            price: '价格',
            'sale-price': '打折价',
            'save-requirements':
                '请填写中英文名称及货号。价格至少为 RM0.01，打折价不可高于原价，重量和整数库存不可为负数。',
            stock: '库存',
            'update-failed': '无法更新规格。',
            'updated-success': '规格更新成功！',
            weight: '重量',
        },
        variations: '规格：',
    },
} as const
