export default {
    actions: {
        add: '添加',
        browse: '浏览',
        cancel: '取消',
        confirm: '确定',
        contact: '联系我们',
        create: '创建',
        delete: '删除',
        details: '详情',
        disable: '停用',
        download: '下载',
        edit: '编辑',
        enable: '启用',
        home: '主页',
        reset: '重置',
        save: '保存',
    },
    alt: {
        'item-image': '商品图片',
        logo: 'e口乐标志',
        'no-image-thumbnail': '暂无图片缩略图',
        'no-results': '无结果',
        'uploaded-image': '已上传图片',
    },
    errors: {
        401: {
            description: '您必须登录账号才能浏览此页面。',
            title: '请先登录',
        },
        403: {
            description: '您无权限浏览此页面。',
            title: '无权限',
        },
        404: {
            description: '您所浏览的页面不存在，可能已迁移或移除。',
            title: '页面不存在',
        },
        default: {
            description: '服务器无法完成请求，请联系我们。',
            title: '出错了',
        },
    },
    filters: {
        'all-items': '显示全部商品',
        'all-origins': '显示全部出产地',
        clicks: '点击量',
        'created-at': '创建时间',
        name: '名称',
        'no-sort': '无排序',
        'only-not-listed': '仅显示未上架',
        'only-out-of-stock': '仅显示无库存',
        sales: '销量',
        'search-items': '搜索名称、货号、规格、出产地或商品描述',
    },
    'image-upload': {
        fill: '填充',
        'invalid-file-size': '所选照片过大，请选择小于 10 MB 的照片。',
        'invalid-file-type': '请选择 JPG、PNG、GIF 或 WebP 格式的照片。',
        original: '原图',
        stretch: '伸展',
        title: '上传照片',
        'upload-failed': '无法上传所选照片。',
        'white-edge': '白边',
    },
    language: {
        chinese: '中文',
        english: 'English',
        label: '语言',
    },
    notifications: {
        error: '错误',
        'generic-error': '发生错误，请稍后重试。',
        success: '操作成功',
    },
    placeholders: {
        'no-items': '无任何商品',
        'no-orders': '无任何订单',
        'no-results': '无结果',
    },
} as const
